title: Property Values ZA
description: A simple search tools / box driven by a single spreadsheet that allows users to check the official property value, as recorded by the municipality, for any properties in their town.

url: https://propertyvalues-za.codeforafrica.org

google_analytics: G-9ZEL1J6JDF
github_url: https://github.com/CodeForAfrica/PropertyValues.ZA
